title: Austin Perez
description: Dedicated Full-Stack Software Engineer experienced with all facets of the software development lifecycle including analysis, design, development, verification and support.
# email: austin@austinp.com
# url: "http://austinp.com"
# twitter_username: jekyllrb
# github_username:  austin4perezident

# Build settings
sass:
  style: compressed
  sourcemap: inline
  # debug_info: true
  line_numbers: true
  line_comments: true
plugins:
  - jekyll-feed